apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest
  template:
    metadata:
      labels:
        app: nest
    spec:
      containers:
        - name: codepix-nest
          image: jhonathanalencar/codepix-nest:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: nest-secret

          volumeMounts:
            - name: nest-volume
              mountPath: /home/node/app/.env
              subPath: .env

      volumes:
        - name: nest-volume
          configMap:
            name: nest-conf
            items:
              - key: env
                path: .env
